import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sean Ormiston | Frontend Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <html lang="en">{children}</html>;
}
